// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "4c9aebd5-9a82-4756-b988-b45d49a46049");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1655997502);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1655997522);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1655998160);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1655998188);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1655997537);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{70c8cf67-dae0-46e1-b8f4-5b935be7a5bf}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1655997471);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 127);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e2c85c3e-5d34-43b0-8706-c1b8e96c57df}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1655998215961");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1656000015961");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1655998202064");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1656019802064");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20220609170544");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1655998161");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20220609170544");
user_pref("browser.startup.homepage_override.mstone", "101.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1655998160);
user_pref("browser.startup.page", 3);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[\"save-to-pocket-button\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"urlbar-container\",\"stop-reload-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"widget-overflow-fixed-list\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":3}");
user_pref("browser.urlbar.placeholderName", "Bing");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1655997490366");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "101.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "9a2087b2f01f46bab6ec7f268f92cba2");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1655998169);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20220609170544");
user_pref("extensions.lastAppVersion", "101.0.1");
user_pref("extensions.lastPlatformVersion", "101.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/plugin");
user_pref("extensions.ui.locale.hidden", false);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"12ff5638-a026-4057-bf2e-537faba1fbed\",\"formautofill@mozilla.org\":\"d6481444-c1ca-494b-9b1a-18a93ea3e3f5\",\"pictureinpicture@mozilla.org\":\"6b6ce9cf-710a-4221-a5e4-9d9fd2b921b6\",\"screenshots@mozilla.org\":\"a3e648b6-6f5e-416d-a225-ecb72c845f58\",\"webcompat-reporter@mozilla.org\":\"4825f7ce-a9b0-4f07-b983-baf1015425ef\",\"webcompat@mozilla.org\":\"b978b2f0-1ba1-47c3-ba30-76f0e0aca813\",\"default-theme@mozilla.org\":\"3c2a6224-4ce8-4502-95ea-db5441a8f028\",\"addons-search-detection@mozilla.com\":\"6fdd1689-7b67-413a-92bb-98f411bc76f7\",\"google@search.mozilla.org\":\"17244558-989a-4ee3-9ea4-440969fee2e9\",\"wikipedia@search.mozilla.org\":\"33d82313-5e38-41a4-ad7d-4ec88de92aa3\",\"bing@search.mozilla.org\":\"9a713889-827c-4089-9b8b-e8d518d62674\",\"ddg@search.mozilla.org\":\"5c8c8c1e-3c75-49a7-ac88-a0d8e2da52ad\",\"baidu@search.mozilla.org\":\"28b72d7b-0a31-4942-8dbc-47467efa29d8\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1655997494);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("nimbus.syncdatastore.tcpByDefault", "{\"slug\":\"tcp-rollout-phase-iii-tcp-on-by-default-for-50-existing-release-profiles\",\"branch\":{\"slug\":\"control\",\"ratio\":1,\"feature\":{\"value\":null,\"enabled\":true,\"featureId\":\"tcpByDefault\"},\"features\":null},\"active\":true,\"enrollmentId\":\"ec166a46-b28a-4a65-9640-780438dc0278\",\"experimentType\":\"nimbus\",\"source\":\"rs-loader\",\"userFacingName\":\"TCP rollout, Phase III (TCP on by default for 50% EXISTING Release profiles)\",\"userFacingDescription\":\"\\\"By default\\\" rollout: Gradually turning on Total Cookie Protection in standard browsing by default for EXISTING user profiles\",\"lastSeen\":\"2022-06-23T15:18:12.176Z\",\"featureIds\":[\"tcpByDefault\"]}");
user_pref("nimbus.syncdatastore.tcpByDefault.enabled", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "3cf135a6-f14d-4c99-9be7-0c393ea138a0");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("toolkit.startup.last_success", 1655998156);
user_pref("toolkit.telemetry.cachedClientID", "c8a44681-29eb-41c2-81aa-62bdbd7bf88c");
user_pref("toolkit.telemetry.previousBuildID", "20220609170544");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
